Redis pubsub logger
dmachard/go-dnscollector pull request #278
Opened 2023-04-19 13:12 UTC by gallypette

Here is my attempt to build a [redis pubsub](https://redis.io/docs/manual/pubsub/) logger.
I started from the tcp client to avoid bringing in new dependencies (like redigo for instance).

2023-04-20 07:51 UTC, dmachard requested changes
Can you update the following code to remove the lint warning ? 	

c.Loggers.RedisPub.Transport = "tcp" 

by

c.Loggers.RedisPub.Transport = SOCKET_TCP

2023-04-20 18:41 UTC, dmachard commented
Look good to me.
Just one thing, can you update the README.md to add this new logger  ?

2023-04-21 07:31 UTC, dmachard approved these changes

2023-04-21 07:32 UTC, merged

2023-04-21 07:48 UTC, gallypette commented
You're welcome. I am glad not having to dig into framestream myself ;)